### ISSUE TITLE
Adding R logo

### ISSUE THREAD

**Issue by Sarani-NS** [yurijserrano/Github-Profile-Readme-Logos#10]
Hi there ! I have no idea how can I contribute, but here is the R programming language logo, if you wanna add it. 

![R_logo](https://github.com/user-attachments/assets/166851c1-1808-49c9-857d-9dd61f837da7)

**Comment by yurijserrano** [comment]
Thank you so much for the contribution @Sarani-NS 

I will be more active on this repo and next week I will be updatign this repo with new logos, so most likely I will be including the R logo in this batch as well.

Stay tunned.

Have a great day.

**Comment by yurijserrano** [comment]
Hello There @Sarani-NS 

I have included the R logo.


Once more, thank you so much for the contribution/

Have a wonderful day and weekend.
