### ISSUE TITLE
coloring issue

### ISSUE THREAD

**Issue by gergelymathe** [yurijserrano/Github-Profile-Readme-Logos#2]
Hi there,

When I use multiple icons, one after an other, the "filling color" of the former icons change according to the original color of the later icon.  Just like this: <img width="156" alt="Screenshot 2022-03-06 at 19 34 20" src="https://user-images.githubusercontent.com/44405670/156937221-43b28a74-8f8f-45e1-8b1e-c084965a6817.png">
Thank you for your help in advance!

**Comment by yurijserrano** [comment]
Truly  Sorry for the delay @gergelymathe 

Are you still having this problem?

**Comment by yurijserrano** [comment]
Since @gergelymathe did **not** answer my question, I am closing this issue.
