### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by codeboyfriend** [yurijserrano/Github-Profile-Readme-Logos#4]
There's a mix up in the text editor and framework list. I can help in fixing that if you don't mind.

**Comment by yurijserrano** [comment]
@codeboyfriend Any help is welcome


But could you please describe the problem with more details?

This way I will be able to reproduce it in my environment.


I am waiting to hear from you

**Comment by codeboyfriend** [comment]
The items listed in the text editor component is the same as the framework component
![Uploading Screenshot_20220915-040756.png…]()
