### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by codeboyfriend** [yurijserrano/Github-Profile-Readme-Logos#5]
The color of the logo has blend with the background on daekmode
![Screenshot_20220915-035200](https://user-images.githubusercontent.com/86895793/190302705-5e79ee9b-a593-45fb-bd79-8e5d4ff45297.png)

**Comment by yurijserrano** [comment]
@codeboyfriend thank you for the feedback

I will be fixing this soon

If you have any new suggestions, please, I would love to hear it.

Soon new updates will come

I wish you a great day
